version: '0.1'

services:

  db:
    image: postgis/postgis:15-3.3-alpine
    container_name: db
    restart: always
    build:
      context: .
      target: db
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    ports:
      - 5432:5432